routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/company','CompanyController')->middleware('auth');
Route::resource('/employees','EmployeeController')->middleware('auth');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $guarded=['id'];



    public function getActionButtonAttribute(){
        return "<a href='".route('employees.edit',$this->id)."'>Edit</a><br>
        <a href='#'onclick='deleteRow(".$this->id.")'' >Delete</a>";
    }

    public  function company(){
     return $this->belongsTo(Company::class);
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Http\Requests\EmployeeRequest;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::with('company')->latest()->paginate(10);
        return view('employee.index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        if ($request->validated()){
            $data = $request->only(['first_name','last_name', 'email', 'phone', 'company_id']);
            $newEmployee = new Employee();
            $newEmployee->fill($data);
            if ($newEmployee->save()) {
                return redirect()->route('employees.index');
            }else{
                return redirect()->withInput($data)->route('employees.create');
            }
        }else{
            return redirect()->withInput($request->all())->route('employees.edit');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('employee.edit',compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        if ($request->validated()){
            $data = $request->only(['first_name','last_name', 'email', 'phone', 'company_id']);
            $employee->fill($data);
            if ($employee->save()) {
                return redirect()->route('employees.index');
            }else{
                return redirect()->withInput($data)->route('employees.edit');
            }
        }else{
            return redirect()->withInput($request->all())->route('employees.edit');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('employees.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="name">First name</label>
            <input class="form-control" type="text" name="first_name" required value="{{old('first_name')}}">
        </div>
        <div class="form-group">
            <label for="name">Last name</label>
            <input class="form-control" type="text" name="last_name" required value="{{old('last_name')}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" value="{{old("email")}}">
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input class="form-control" type="text" name="phone" value="{{old("phone")}}">
        </div>
        <div class="form-group">
            <label for="company_id">Company</label>
            <select class="form-control" name="company_id">
                @foreach(\App\Company::all() as $company)
                    <option value="{{$company->id}}">{{$company->name}}</option>
                @endforeach
            </select>
        </div>

        <button class="button-primary" type="submit">Save</button>
    </form>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('employees.update',$employee->id)}}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">First name</label>
            <input class="form-control" type="text" name="first_name" required value="{{$employee->first_name}}">
        </div>
        <div class="form-group">
            <label for="name">Last name</label>
            <input class="form-control" type="text" name="last_name" required value="{{$employee->last_name}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" value="{{$employee->email}}">
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input class="form-control" type="text" name="phone" value="{{$employee->phone}}">
        </div>
        <div class="form-group">
            <label for="company_id">Company</label>
            <select class="form-control" name="company_id">
                @foreach(\App\Company::all() as $company)
                    <option value="{{$company->id}}" @if($company->id==$employee->id) selected @endif>{{$company->name}}</option>
                @endforeach
            </select>
        </div>

        <button class="button-primary" type="submit">Save</button>
    </form>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('page_title')
    Employees
@endsection

@push('after_styles')
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
@endpush

@push('scripts-header')

@endpush



@section('content')
    <div class="row">
        <div class="col-1 col-offset-11">
            <a href="{{route('employees.create')}}">Add</a>
        </div>

    </div>

    <div class="row">
        <div class="col">
            <table class="table" id="table-employees">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>E-mail</th>
                    <th>Phone</th>
                    <th>Company</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($employees as $employee)
                    <tr>
                        <td>{{$employee->first_name}}</td>
                        <td>{{$employee->last_name}}</td>
                        <td>{{$employee->email}}</td>
                        <td>{{$employee->phone}}</td>
                        <td>{{$employee->company->name}}</td>
                        <td>{!! $employee->actionButton !!}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$employees->links()}}
        </div>

    </div>

    <script>
        function deleteRow(id){
            if (confirm("Delete employee?")) {
                $.ajaxSetup({
                    headers:{'X-CSRF-Token':$('input[name=_token]').val()}
                });

                $.ajax({
                    url : '/employees/'+id,
                    type : 'DELETE',
                    success : function(data) {
                        location.reload();
                    },
                    error: function(e) {
                        console.log(e);
                    }

                });
            }
        }
    </script>

@endsection

@push('scripts-footer')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script>
    var table = $('#table-employees').DataTable({
        processing: true,
        serverSide: false,
        paging: false,
    });
</script>
@endpush