routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/company','CompanyController')->middleware('auth');
Route::resource('/employees','EmployeeController')->middleware('auth');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{

    protected $guarded=['id'];



    public function getActionButtonAttribute(){
        return "<a href='".route('company.edit',$this->id)."'>Edit</a><br>
        <a href='#' onclick='deleteRow(".$this->id.")'>Delete</a>";
    }


    public function uploadLogo($file)
    {

        $tmpFileName = time() . '-' . $file->getClientOriginalName();
        info(storage_path('/').$tmpFileName);
        $file->move(storage_path('/app/public/'), $tmpFileName);
        $this->logo = $tmpFileName;
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Http\Requests\CompanyRequest;
use App\Mail\CompanyCreated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::latest()->paginate(10);
        return view('company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        if ($request->validated()){
            $data = $request->only(['name','email','website']);
            $newCompany = new Company();
            $newCompany->fill($data);
            if ($request->hasFile('logo')) {
                info('have logo');
                $newCompany->uploadLogo($request->file('logo'));
            }

            if ($newCompany->save()) {
                Mail::to($request->user())->send(new CompanyCreated($newCompany));
                return redirect()->route('company.index');
            }else{
                return redirect()->withInput($data)->route('company.create');
            }
        }else{
            return redirect()->withInput($request->all())->route('company.edit');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {
        if ($request->validated()){
            $data = $request->only(['name','email','website']);
            $company->fill($data);
            if ($request->hasFile('logo')) {
                $company->uploadLogo($request->file('logo'));
            }
            if ($company->save()) {
                return redirect()->route('company.index');
            }else{
                return redirect()->withInput($data)->route('company.edit');
            }
        }else{
            return redirect()->withInput($request->all())->route('company.edit');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('company.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input class="form-control" type="text" name="name" required value="{{old('name')}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control"type="email" name="email" value="{{old("email")}}">
        </div>
        <div class="form-group">
            <label for="website">Web</label>
            <input class="form-control"type="text" name="website" value="{{old("website")}}">
        </div>
        <div class="form-group">
            <label for="logo">Logo</label>
            <input type="file" name="logo">
        </div>

        <button  class="button-primary" type="submit">Save</button>
    </form>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form  action="{{route('company.update',$company->id)}}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input class="form-control" type="text" name="name" required value="{{$company->name}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" value="{{$company->email}}">
        </div>
        <div class="form-group">
            <label for="website">Web</label>
            <input class="form-control" type="text" name="website" value="{{$company->website}}">
        </div>
        <div class="form-group">
            <label for="logo">Logo</label>
            <input class="form-control" type="file" name="logo">
        </div>
        <button class="button-primary" type="submit">Save</button>
    </form>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('page_title')
    Companies
@endsection


@push('scripts-header')

@endpush

@push('after_styles')
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
@endpush

@section('content')
    <div class="row">
        <div class="col">
            <a class="button-primary" href="{{route('company.create')}}">Add</a>
        </div>

    </div>

    <div class="row">
        <div class="col">
            <table class="table" id="table-company">
                <thead>
                <td>Name</td>
                <td>E-mail</td>
                <td>Web</td>
                <td>Logo</td>
                <td>Action</td>
                </thead>
                <tbody>
                @foreach($companies as $company)
                    <tr>
                        <td>{{$company->name}}</td>
                        <td>{{$company->email}}</td>
                        <td>{{$company->website}}</td>
                        <td>@if($company->logo) <img src="/storage/{{$company->logo}}" height="200" width="200">@endif</td>
                        <td>{!! $company->actionButton !!}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$companies->links()}}
        </div>

    </div>

    <script>
        function deleteRow(id){
            if (confirm("Delete company?")) {
                $.ajaxSetup({
                    headers:{'X-CSRF-Token':$('input[name=_token]').val()}
                });

                $.ajax({
                    url : '/company/'+id,
                    type : 'DELETE',
                    success : function(data) {
                        location.reload();
                    },
                    error: function(e) {
                        console.log(e);
                    }

                });
            }
        }
    </script>
@endsection

@push('scripts-footer')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script>
    var table = $('#table-company').DataTable({
        processing: true,
        serverSide: false,
        paging:false,
    });
</script>
@endpush